# Form implementation generated from reading ui file 'ui/timer.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 300)
        Form.setStyleSheet("background-color: #74708C")
        self.btn_30sec = QtWidgets.QPushButton(parent=Form)
        self.btn_30sec.setGeometry(QtCore.QRect(162, 155, 70, 40))
        self.btn_30sec.setStyleSheet("background-color: #9E99BF;\n"
"color: #F2EEB6;\n"
"    font-family: Inter;\n"
"    font-size: 12px;\n"
"border-radius: 10px;")
        self.btn_30sec.setObjectName("btn_30sec")
        self.btn_1m = QtWidgets.QPushButton(parent=Form)
        self.btn_1m.setGeometry(QtCore.QRect(265, 154, 70, 40))
        self.btn_1m.setStyleSheet("background-color: #9E99BF;\n"
"color: #F2EEB6;\n"
"    font-family: Inter;\n"
"    font-size: 12px;\n"
"border-radius: 10px;")
        self.btn_1m.setObjectName("btn_1m")
        self.btn_5m = QtWidgets.QPushButton(parent=Form)
        self.btn_5m.setGeometry(QtCore.QRect(368, 154, 70, 40))
        self.btn_5m.setStyleSheet("background-color: #9E99BF;\n"
"color: #F2EEB6;\n"
"    font-family: Inter;\n"
"    font-size: 12px;\n"
"border-radius: 10px;")
        self.btn_5m.setObjectName("btn_5m")
        self.btn_run = QtWidgets.QPushButton(parent=Form)
        self.btn_run.setGeometry(QtCore.QRect(10, 250, 580, 40))
        self.btn_run.setStyleSheet("background-color: #7A7EBF;\n"
"border-radius: 10px;")
        self.btn_run.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\../assets/icon/btn_run.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_run.setIcon(icon)
        self.btn_run.setObjectName("btn_run")
        self.timer = QtWidgets.QTimeEdit(parent=Form)
        self.timer.setGeometry(QtCore.QRect(213, 106, 173, 48))
        self.timer.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.timer.setAutoFillBackground(False)
        self.timer.setStyleSheet("QTimeEdit {\n"
"    font-family: Inter;\n"
"    font-size: 40px;\n"
"    font-weight: normal;\n"
"    color: #F2EEB6; /* Цвет текста */\n"
"    background: transparent; /* Прозрачный фон */\n"
"    border: none; /* Убираем границы */\n"
"}\n"
"\n"
"QTimeEdit {\n"
"/*    background-color: rgba(242, 238, 182, 0.1); /* Легкий оттенок */\n"
"    border-radius: 5px; /* Скругление углов */\n"
"}\n"
"\n"
"QTimeEdit::up-button, QTimeEdit::down-button {\n"
"    width: 0px;\n"
"    height: 0px;\n"
"    border: none;\n"
"}\n"
"\n"
"")
        self.timer.setObjectName("timer")
        self.chkb_mute = QtWidgets.QCheckBox(parent=Form)
        self.chkb_mute.setGeometry(QtCore.QRect(10, 10, 40, 40))
        self.chkb_mute.setMinimumSize(QtCore.QSize(33, 33))
        self.chkb_mute.setStyleSheet("")
        self.chkb_mute.setText("")
        self.chkb_mute.setCheckable(True)
        self.chkb_mute.setObjectName("chkb_mute")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_30sec.setText(_translate("Form", "+30s"))
        self.btn_1m.setText(_translate("Form", "+1m"))
        self.btn_5m.setText(_translate("Form", "+5m"))
        self.timer.setDisplayFormat(_translate("Form", "hh:mm:ss"))
