# Form implementation generated from reading ui file 'ui/main.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 300)
        MainWindow.setMinimumSize(QtCore.QSize(600, 300))
        MainWindow.setMaximumSize(QtCore.QSize(600, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\../assets/logo.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background: #5B7065")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(600, 300))
        self.centralwidget.setMaximumSize(QtCore.QSize(600, 300))
        self.centralwidget.setObjectName("centralwidget")
        self.btn_run = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_run.setGeometry(QtCore.QRect(30, 243, 540, 27))
        self.btn_run.setMinimumSize(QtCore.QSize(540, 27))
        self.btn_run.setMaximumSize(QtCore.QSize(540, 27))
        self.btn_run.setStyleSheet("QPushButton {\n"
"background-color: #304040;\n"
"color: #C9D1C8;\n"
"font-family: Inter;\n"
"font-size: 15px;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #374A4A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: #04202C;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"background-color: #03161F;\n"
"}\n"
"")
        self.btn_run.setObjectName("btn_run")
        self.timeEdit = QtWidgets.QTimeEdit(parent=self.centralwidget)
        self.timeEdit.setGeometry(QtCore.QRect(213, 126, 173, 48))
        self.timeEdit.setMinimumSize(QtCore.QSize(173, 48))
        self.timeEdit.setMaximumSize(QtCore.QSize(173, 48))
        self.timeEdit.setStyleSheet("QTimeEdit {\n"
"    font-family: Inter;\n"
"    font-size: 40px;\n"
"    font-weight: normal;\n"
"    color: #C9D1C8;\n"
"    background: transparent; \n"
"    border: none;\n"
"}\n"
"\n"
"QTimeEdit {\n"
"    border-radius: 5px; \n"
"}\n"
"\n"
"QTimeEdit::up-button, QTimeEdit::down-button {\n"
"    width: 0px;\n"
"    height: 0px;\n"
"    border: none;\n"
"}\n"
"\n"
"")
        self.timeEdit.setObjectName("timeEdit")
        self.btn_30sec = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_30sec.setGeometry(QtCore.QRect(140, 174, 100, 27))
        self.btn_30sec.setMinimumSize(QtCore.QSize(100, 27))
        self.btn_30sec.setMaximumSize(QtCore.QSize(100, 27))
        self.btn_30sec.setStyleSheet("QPushButton {\n"
"background-color: #304040;\n"
"color: #C9D1C8;\n"
"font-family: Inter;\n"
"font-size: 15px;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #374A4A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: #04202C;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"background-color: #03161F;\n"
"}\n"
"")
        self.btn_30sec.setObjectName("btn_30sec")
        self.btn_1min = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_1min.setGeometry(QtCore.QRect(250, 174, 100, 27))
        self.btn_1min.setMinimumSize(QtCore.QSize(100, 27))
        self.btn_1min.setMaximumSize(QtCore.QSize(100, 27))
        self.btn_1min.setStyleSheet("QPushButton {\n"
"background-color: #304040;\n"
"color: #C9D1C8;\n"
"font-family: Inter;\n"
"font-size: 15px;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #374A4A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: #04202C;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"background-color: #03161F;\n"
"}\n"
"")
        self.btn_1min.setObjectName("btn_1min")
        self.btn_5min = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_5min.setGeometry(QtCore.QRect(360, 174, 100, 27))
        self.btn_5min.setMinimumSize(QtCore.QSize(100, 27))
        self.btn_5min.setMaximumSize(QtCore.QSize(100, 27))
        self.btn_5min.setStyleSheet("QPushButton {\n"
"background-color: #304040;\n"
"color: #C9D1C8;\n"
"font-family: Inter;\n"
"font-size: 15px;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #374A4A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: #04202C;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"background-color: #03161F;\n"
"}\n"
"")
        self.btn_5min.setObjectName("btn_5min")
        self.btn_fun_volume = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_fun_volume.setGeometry(QtCore.QRect(30, 30, 100, 27))
        self.btn_fun_volume.setMinimumSize(QtCore.QSize(100, 27))
        self.btn_fun_volume.setMaximumSize(QtCore.QSize(100, 27))
        self.btn_fun_volume.setStyleSheet("QPushButton {\n"
"background-color: #304040;\n"
"color: #C9D1C8;\n"
"font-family: Inter;\n"
"font-size: 12px;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #374A4A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: #04202C;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"background-color: #03161F;\n"
"}\n"
"")
        self.btn_fun_volume.setObjectName("btn_fun_volume")
        self.btn_fun_lock = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_fun_lock.setGeometry(QtCore.QRect(250, 30, 100, 27))
        self.btn_fun_lock.setMinimumSize(QtCore.QSize(100, 27))
        self.btn_fun_lock.setMaximumSize(QtCore.QSize(100, 27))
        self.btn_fun_lock.setStyleSheet("QPushButton {\n"
"background-color: #304040;\n"
"color: #C9D1C8;\n"
"font-family: Inter;\n"
"font-size: 12px;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #374A4A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: #04202C;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"background-color: #03161F;\n"
"}\n"
"")
        self.btn_fun_lock.setObjectName("btn_fun_lock")
        self.btn_fun_power = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_fun_power.setGeometry(QtCore.QRect(470, 30, 100, 27))
        self.btn_fun_power.setMinimumSize(QtCore.QSize(100, 27))
        self.btn_fun_power.setMaximumSize(QtCore.QSize(100, 27))
        self.btn_fun_power.setStyleSheet("QPushButton {\n"
"background-color: #304040;\n"
"color: #C9D1C8;\n"
"font-family: Inter;\n"
"font-size: 12px;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #374A4A;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: #04202C;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"background-color: #03161F;\n"
"}\n"
"")
        self.btn_fun_power.setObjectName("btn_fun_power")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Smart Sleep Timer"))
        self.btn_run.setText(_translate("MainWindow", "start"))
        self.timeEdit.setDisplayFormat(_translate("MainWindow", "hh:mm:ss"))
        self.btn_30sec.setText(_translate("MainWindow", "+30 sec"))
        self.btn_1min.setText(_translate("MainWindow", "+1 min"))
        self.btn_5min.setText(_translate("MainWindow", "+5 min"))
        self.btn_fun_volume.setText(_translate("MainWindow", "volume: on"))
        self.btn_fun_lock.setText(_translate("MainWindow", "lock screen: on"))
        self.btn_fun_power.setText(_translate("MainWindow", "power: on"))
