# Form implementation generated from reading ui file 'ui/timer.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(600, 300)
        Form.setStyleSheet("background-color: #BFBFBF")
        self.btn_30sec = QtWidgets.QPushButton(parent=Form)
        self.btn_30sec.setGeometry(QtCore.QRect(162, 155, 70, 40))
        self.btn_30sec.setStyleSheet("QPushButton {\n"
"background-color: #262626;\n"
"color: #F2F2F2;\n"
"font-family: Inter;\n"
"font-size: 12px;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #1F1F1F;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: #141414;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"background-color: #0D0D0D;\n"
"\n"
"}\n"
"")
        self.btn_30sec.setObjectName("btn_30sec")
        self.btn_1m = QtWidgets.QPushButton(parent=Form)
        self.btn_1m.setGeometry(QtCore.QRect(265, 154, 70, 40))
        self.btn_1m.setStyleSheet("QPushButton {\n"
"background-color: #262626;\n"
"color: #F2F2F2;\n"
"font-family: Inter;\n"
"font-size: 12px;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #1F1F1F;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: #141414;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"background-color: #0D0D0D;\n"
"\n"
"}\n"
"")
        self.btn_1m.setObjectName("btn_1m")
        self.btn_5m = QtWidgets.QPushButton(parent=Form)
        self.btn_5m.setGeometry(QtCore.QRect(368, 154, 70, 40))
        self.btn_5m.setStyleSheet("QPushButton {\n"
"background-color: #262626;\n"
"color: #F2F2F2;\n"
"font-family: Inter;\n"
"font-size: 12px;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #1F1F1F;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: #141414;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"background-color: #0D0D0D;\n"
"\n"
"}\n"
"")
        self.btn_5m.setObjectName("btn_5m")
        self.btn_run = QtWidgets.QPushButton(parent=Form)
        self.btn_run.setGeometry(QtCore.QRect(10, 250, 580, 40))
        self.btn_run.setStyleSheet("QPushButton {\n"
"background-color: #262626;\n"
"color: #F2F2F2;\n"
"font-family: Inter;\n"
"font-size: 12px;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #1F1F1F;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: #141414;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"background-color: #0D0D0D;\n"
"\n"
"}\n"
"")
        self.btn_run.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\../assets/icon/btn_run.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_run.setIcon(icon)
        self.btn_run.setIconSize(QtCore.QSize(28, 28))
        self.btn_run.setObjectName("btn_run")
        self.timer = QtWidgets.QTimeEdit(parent=Form)
        self.timer.setGeometry(QtCore.QRect(213, 106, 173, 48))
        self.timer.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.timer.setAutoFillBackground(False)
        self.timer.setStyleSheet("QTimeEdit {\n"
"    font-family: Inter;\n"
"    font-size: 40px;\n"
"    font-weight: normal;\n"
"    color: #F2F2F2; /* Цвет текста */\n"
"    background: transparent; /* Прозрачный фон */\n"
"    border: none; /* Убираем границы */\n"
"}\n"
"\n"
"QTimeEdit {\n"
"/*    background-color: rgba(242, 238, 182, 0.1); /* Легкий оттенок */\n"
"    border-radius: 5px; /* Скругление углов */\n"
"}\n"
"\n"
"QTimeEdit::up-button, QTimeEdit::down-button {\n"
"    width: 0px;\n"
"    height: 0px;\n"
"    border: none;\n"
"}\n"
"\n"
"")
        self.timer.setObjectName("timer")
        self.chkb_mute = QtWidgets.QCheckBox(parent=Form)
        self.chkb_mute.setGeometry(QtCore.QRect(10, 10, 40, 40))
        self.chkb_mute.setMinimumSize(QtCore.QSize(33, 33))
        self.chkb_mute.setStyleSheet("            QCheckBox{\n"
"background: transparent;}            \n"
"QCheckBox::indicator {\n"
"                background: transparent;\n"
"                border: none;\n"
"            }")
        self.chkb_mute.setText("")
        self.chkb_mute.setCheckable(True)
        self.chkb_mute.setObjectName("chkb_mute")
        self.label_mute = QtWidgets.QLabel(parent=Form)
        self.label_mute.setEnabled(True)
        self.label_mute.setGeometry(QtCore.QRect(15, 16, 28, 28))
        self.label_mute.setStyleSheet("background: transparent;\n"
"")
        self.label_mute.setText("")
        self.label_mute.setPixmap(QtGui.QPixmap("ui\\../assets/icon/unmute.svg"))
        self.label_mute.setScaledContents(False)
        self.label_mute.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_mute.setObjectName("label_mute")
        self.label_mute_bkg = QtWidgets.QLabel(parent=Form)
        self.label_mute_bkg.setGeometry(QtCore.QRect(10, 10, 40, 40))
        self.label_mute_bkg.setStyleSheet("QLabel {\n"
"background: #262626;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QLabel:hover {\n"
"background: #1F1F1F;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"        background-color: #141414;\n"
"}\n"
"\n"
"QLabel:disabled {\n"
"        background-color: #0D0D0D;\n"
"}")
        self.label_mute_bkg.setText("")
        self.label_mute_bkg.setObjectName("label_mute_bkg")
        self.label_mute_bkg.raise_()
        self.label_mute.raise_()
        self.btn_30sec.raise_()
        self.btn_1m.raise_()
        self.btn_5m.raise_()
        self.btn_run.raise_()
        self.timer.raise_()
        self.chkb_mute.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_30sec.setText(_translate("Form", "+30s"))
        self.btn_1m.setText(_translate("Form", "+1m"))
        self.btn_5m.setText(_translate("Form", "+5m"))
        self.timer.setDisplayFormat(_translate("Form", "hh:mm:ss"))
