name: build and release app

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: check rep
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: install dependencies
        run: pip install -r requirements.txt pyinstaller

      - name: build
        run: pyinstaller --name 'smart_sleep_timer-windows-amd64' --windowed --onefile  --icon=assets/logo.ico main.py

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Smart-Sleep-Timer
          path: dist/smart_sleep_timer-windows-amd64.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download built EXE
        uses: actions/download-artifact@v4
        with:
          name: Smart-Sleep-Timer
          path: dist

      - name: Extract version from tag
        id: extract_version
        run: |
          echo "TAG_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/smart_sleep_timer-windows-amd64.exe
          body: |
            # Smart Sleep Timer ${{ steps.extract_version.outputs.TAG_VERSION }}
            
            ## How to Use (windows)?
            
            1. Download the application.
            
            2. Run `smart_sleep_timer-windows-amd64.exe`.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}